# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: your-express-app-image:latest
          ports:
            - containerPort: 3000

# Service
apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

# Ingress Class
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx

# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: your-hostname.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-app-service
                port:
                  number: 80
