name: Deploy to ECR

on:
 
  push:
    branches: [ dev ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker images
      run: |
        for dockerfile in $(find . -name "Dockerfile" -type f); do
          dir=$(dirname $dockerfile)
          tag=your-dockerhub-username/$(basename $dir):${{ github.sha }}
          docker build -t $tag $dir
          docker push $tag
        done
